In [8]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
import os
import numpy as np

per_tox_folder = 'datasets\MT_dataset\per_toxicity_csv_542'
os.listdir(per_tox_folder)

['Aspiration_M06_542.csv',
 'Dysphagia_M06_542.csv',
 'Sticky_M06_542.csv',
 'Taste_M06_542.csv',
 'Xerostomia_M06_542.csv']

## TASTE

In [10]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score

# Load the CSV file
dfX_path = os.path.join(per_tox_folder, 'Taste_M06_542.csv')
data = pd.read_csv(dfX_path, delimiter=';', index_col=0)

# Define the features and target
features = ['Parotid_meandose', 'OralCavity_Ext_meandose', 'Age'] # Replace with your actual feature column names
target = 'Taste_M06' # Replace with your actual target column name

# Split the data into training and testing sets based on the "Split" column
train_data = data[data['Split'] != 'test']
test_data = data[data['Split'] == 'test']

# Separate features and target for training and testing
X_train = train_data[features]
y_train = train_data[target]
X_test = test_data[features]
y_test = test_data[target]

# Create and train the logistic regression model
model = LogisticRegression(C=1e10)
model.fit(X_train, y_train)

# Make predictions on the test set
train_predictions = model.predict_proba(X_train)[:, 1]
test_predictions = model.predict_proba(X_test)[:, 1]

# Evaluate the model using AUC
train_auc = roc_auc_score(y_train, train_predictions)
print(f'Train AUC: {train_auc}')
test_auc = roc_auc_score(y_test, test_predictions)
print(f'Test AUC: {test_auc}')

# Print the coefficient weights
print("Coefficient weights:")
print(model.coef_)
print(model.intercept_)

Train AUC: 0.713825288778878
Test AUC: 0.7062567713976166
Coefficient weights:
[[1.78419956e-03 3.88627928e-02 3.65744118e+00]]
[-4.81568352]


## ASPIRATION

In [11]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score

# Load the CSV file
dfX_path = os.path.join(per_tox_folder, 'Aspiration_M06_542.csv')

data = pd.read_csv(dfX_path, delimiter=';', index_col=0)

# Define the features and target
features = ['PCM_Med_meandose', 'Aspiration_W01_Een_beetje', 'Aspiration_W01_Nogal_Heel_erg'] # Replace with your actual feature column names
target = 'Aspiration_M06' # Replace with your actual target column name

# Split the data into training and testing sets based on the "Split" column
train_data = data[data['Split'] != 'test']
test_data = data[data['Split'] == 'test']

# Separate features and target for training and testing
X_train = train_data[features]
y_train = train_data[target]
X_test = test_data[features]
y_test = test_data[target]

# Create and train the logistic regression model
model = LogisticRegression(C=1e20)
model.fit(X_train, y_train)

# Make predictions on the test set
train_predictions = model.predict_proba(X_train)[:, 1]
test_predictions = model.predict_proba(X_test)[:, 1]

# Evaluate the model using AUC
train_auc = roc_auc_score(y_train, train_predictions)
print(f'Train AUC: {train_auc}')
test_auc = roc_auc_score(y_test, test_predictions)
print(f'Test AUC: {test_auc}')

# Print the coefficient weights
print("Coefficient weights:")
print(model.coef_)
print(model.intercept_)

Train AUC: 0.7564822868426619
Test AUC: 0.740751879699248
Coefficient weights:
[[0.01633497 1.43416847 2.08456999]]
[-3.78413007]


## STICKY

In [12]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score

# Load the CSV file
dfX_path = os.path.join(per_tox_folder, 'Sticky_M06_542.csv')

data = pd.read_csv(dfX_path, delimiter=';', index_col=0)

# Define the features and target
features = ['Submandibular_meandose', 'Parotid_meandose', 'Sticky_W01_Een_beetje', 'Sticky_W01_Nogal_Heel_erg'] # Replace with your actual feature column names
target = 'Sticky_M06' # Replace with your actual target column name

# Split the data into training and testing sets based on the "Split" column
train_data = data[data['Split'] != 'test']
test_data = data[data['Split'] == 'test']

# Separate features and target for training and testing
X_train = train_data[features]
y_train = train_data[target]
X_test = test_data[features]
y_test = test_data[target]

# Create and train the logistic regression model
model = LogisticRegression(C=1e10)
model.fit(X_train, y_train)

# Make predictions on the test set
train_predictions = model.predict_proba(X_train)[:, 1]
test_predictions = model.predict_proba(X_test)[:, 1]

# Evaluate the model using AUC
train_auc = roc_auc_score(y_train, train_predictions)
print(f'Train AUC: {train_auc}')
test_auc = roc_auc_score(y_test, test_predictions)
print(f'Test AUC: {test_auc}')

# Print the coefficient weights
print("Coefficient weights:")
print(model.coef_)
print(model.intercept_)

Train AUC: 0.7069495514046182
Test AUC: 0.7152844744455159
Coefficient weights:
[[ 0.02930961 -0.0096606   0.77939905  1.52146509]]
[-2.24618638]


# Xerostomia

In [14]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score

# Load the CSV file
dfX_path = os.path.join(per_tox_folder, 'Xerostomia_M06_542.csv')

data = pd.read_csv(dfX_path, delimiter=';', index_col=0)

# Define the features and target
features = ['Parotid_meandose', 'Submandibular_meandose', 'Xerostomia_W01_Een_beetje', 'Xerostomia_W01_Nogal_Heel_erg'] # Replace with your actual feature column names
subfeatures = [["Parotid_meandose", 'Xerostomia_W01_Een_beetje', 'Xerostomia_W01_Nogal_Heel_erg'], ["Submandibular_meandose", 'Xerostomia_W01_Een_beetje', 'Xerostomia_W01_Nogal_Heel_erg']]
target = 'Xerostomia_M06' # Replace with your actual target column name
nr_submodels = len(subfeatures)
# Split the data into training and testing sets based on the "Split" column
train_data = data[data['Split'] != 'test']
test_data = data[data['Split'] == 'test']

coeffs_dict_list = []
for feature_subset in subfeatures:
    # Separate features and target for training and testing
    X_train = train_data[feature_subset]
    y_train = train_data[target]
    X_test = test_data[feature_subset]
    y_test = test_data[target]

    # Create and train the logistic regression model
    model = LogisticRegression(C=1e10)
    model.fit(X_train, y_train)

    # Make predictions on the test set
    train_predictions = model.predict_proba(X_train)[:, 1]
    test_predictions = model.predict_proba(X_test)[:, 1]

    # Evaluate the model using AUC
    train_auc = roc_auc_score(y_train, train_predictions)
    print(f'Train AUC: {train_auc}')
    test_auc = roc_auc_score(y_test, test_predictions)
    print(f'Test AUC: {test_auc}')

    # Print the coefficient weights
    print("Coefficient weights:")
    print(model.coef_)
    print(model.intercept_)
    print("\n")

    keys = ['intercept'] + feature_subset
    values = np.append(model.intercept_, model.coef_)
    coeffs_i_dict = {k: v for (k, v) in zip(keys, values)}
    coeffs_dict_list.append(coeffs_i_dict)




Train AUC: 0.7377959313161756
Test AUC: 0.755066170388751
Coefficient weights:
[[0.04937927 0.90002466 1.60151013]]
[-1.86938216]


Train AUC: 0.7506576251470569
Test AUC: 0.7582712985938793
Coefficient weights:
[[0.04233827 0.91955558 1.56529491]]
[-2.7868369]




In [16]:
# Construct coefficients of final model
lr_coefficients = []
for f in ['intercept'] + features:
    coeff_i = 0
    # For-loop over coefficients of submodels
    for d_i in coeffs_dict_list:
        if f in d_i.keys():
            coeff_i += d_i[f]

    lr_coefficients.append(coeff_i / nr_submodels)


lr_coefficients

[-2.328109526646235,
 0.024689635222134607,
 0.021169136248035073,
 0.909790121764723,
 1.5834025208735738]

In [10]:
coeffs_list

[{'intercept': -1.8693821564605617,
  'Parotid_meandose': 0.049379270444269215,
  'Xerostomia_W01_Een_beetje': 0.9000246635313223,
  'Xerostomia_W01_Nogal_Heel_erg': 1.6015101336841695},
 {'intercept': -2.7868368968319084,
  'Submandibular_meandose': 0.042338272496070146,
  'Xerostomia_W01_Een_beetje': 0.9195555799981237,
  'Xerostomia_W01_Nogal_Heel_erg': 1.565294908062978}]