In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedShuffleSplit, ShuffleSplit

def stratified_cumulative_sampling(X, y, sample_sizes, step_size =10, random_state=42):
    """
    Perform stratified cumulative sampling.
    
    Parameters:
        X (array-like): Feature matrix.
        y (array-like): Target labels for stratification.
        sample_sizes (list): List of cumulative sample sizes (e.g., [100, 200, 300, ...]).
        random_state (int): Random seed for reproducibility.
    
    Returns:
        dict: Dictionary containing subsets with keys as sample sizes.
    """
    sampled_indices = set()
    subsets = {}

    for size in sample_sizes:
        print(size)
        remaining_indices = list(set(range(len(X))) - sampled_indices)
        
        strat_split = ShuffleSplit(n_splits=1, train_size=size - len(sampled_indices), random_state=random_state)
        new_indices, _ = next(strat_split.split(X[remaining_indices])) # , y[remaining_indices]))
        new_indices = np.array(remaining_indices)[new_indices]  # Convert to original index space
        
        sampled_indices.update(new_indices)
        subsets[size] = X[list(sampled_indices)]
    
    return subsets

# Example usage
np.random.seed(42)
X = np.random.rand(20, 3)  # 1100 samples, 10 features
y = np.random.randint(0, 1, 20)  # 3 classes for stratification

sample_sizes = list(range(3, 11, 1))
subsets = stratified_cumulative_sampling(X, y, sample_sizes)

# Checking sizes
for size, (X_subset) in subsets.items():
    print(f"Sample size {size}: {X_subset.shape}")
    print(X_subset)


3
4
5
6
7
8
9
10
Sample size 3: (3, 3)
[[0.60754485 0.17052412 0.06505159]
 [0.03438852 0.9093204  0.25877998]
 [0.43194502 0.29122914 0.61185289]]
Sample size 4: (4, 3)
[[0.60754485 0.17052412 0.06505159]
 [0.13949386 0.29214465 0.36636184]
 [0.03438852 0.9093204  0.25877998]
 [0.43194502 0.29122914 0.61185289]]
Sample size 5: (5, 3)
[[0.43194502 0.29122914 0.61185289]
 [0.13949386 0.29214465 0.36636184]
 [0.45606998 0.78517596 0.19967378]
 [0.60754485 0.17052412 0.06505159]
 [0.03438852 0.9093204  0.25877998]]
Sample size 6: (6, 3)
[[0.43194502 0.29122914 0.61185289]
 [0.13949386 0.29214465 0.36636184]
 [0.45606998 0.78517596 0.19967378]
 [0.51423444 0.59241457 0.04645041]
 [0.60754485 0.17052412 0.06505159]
 [0.03438852 0.9093204  0.25877998]]
Sample size 7: (7, 3)
[[0.43194502 0.29122914 0.61185289]
 [0.13949386 0.29214465 0.36636184]
 [0.45606998 0.78517596 0.19967378]
 [0.51423444 0.59241457 0.04645041]
 [0.60754485 0.17052412 0.06505159]
 [0.94888554 0.96563203 0.80839735]
 [0.0

In [ ]:
key_to_check = 5
if key_to_check in subsets:
    print(f"Key {key_to_check} exists in the dictionary.")
else:
    print(f"Key {key_to_check} does not exist in the dictionary.")

In [122]:
import pandas as pd
import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedShuffleSplit, ShuffleSplit
import os
# Example usage
np.random.seed(42)
X = np.random.rand(10, 3)  # 10 samples, 3 features


df = pd.DataFrame(X)
df

,0,1,2
0,0.374540,0.950714,0.731994
1,0.598658,0.156019,0.155995
2,0.058084,0.866176,0.601115
3,0.708073,0.020584,0.969910
4,0.832443,0.212339,0.181825
5,0.183405,0.304242,0.524756
6,0.431945,0.291229,0.611853
7,0.139494,0.292145,0.366362
8,0.456070,0.785176,0.199674
9,0.514234,0.592415,0.046450


In [21]:
#sampled_indices = set()
sample_sizes = [1,2,3,4,5]
random_state = 42

pseudo_config = {"sampled_indices" : []}

In [45]:
#sampled_indices = set()
sample_sizes = [1,2,3,4,5]
random_state = 42

pseudo_config = {"sampled_indices" : []}



for sample_size in sample_sizes:
    print(sample_size)
    remaining_indices = list(set(range(len(df))) - set(pseudo_config['sampled_indices']))
    required_samples = sample_size - len(pseudo_config['sampled_indices'])

    shuffle_split = ShuffleSplit(n_splits=1, train_size=required_samples, random_state=random_state)
    new_indices, _ = next(shuffle_split.split(remaining_indices))
    new_indices = np.array(remaining_indices)[new_indices]  # Convert to original index space

    pseudo_config['sampled_indices'] += list(new_indices)
    #pseudo_config['sampled_indices'] = list(set(pseudo_config['sampled_indices']))

    final_indices = list(pseudo_config['sampled_indices'])[:sample_size]
    print(df.iloc[final_indices].head())

1
          0         1         2
6  0.431945  0.291229  0.611853
2
          0         1         2
6  0.431945  0.291229  0.611853
7  0.139494  0.292145  0.366362
3
          0         1         2
6  0.431945  0.291229  0.611853
7  0.139494  0.292145  0.366362
8  0.456070  0.785176  0.199674
4
          0         1         2
6  0.431945  0.291229  0.611853
7  0.139494  0.292145  0.366362
8  0.456070  0.785176  0.199674
9  0.514234  0.592415  0.046450
5
          0         1         2
6  0.431945  0.291229  0.611853
7  0.139494  0.292145  0.366362
8  0.456070  0.785176  0.199674
9  0.514234  0.592415  0.046450
3  0.708073  0.020584  0.969910


In [46]:
#sampled_indices = set()
sample_sizes = [6]
random_state = 101

for sample_size in sample_sizes:
    print(sample_size)
    remaining_indices = list(set(range(len(df))) - set(pseudo_config['sampled_indices']))
    required_samples = sample_size - len(pseudo_config['sampled_indices'])

    shuffle_split = ShuffleSplit(n_splits=1, train_size=required_samples, random_state=random_state)
    new_indices, _ = next(shuffle_split.split(remaining_indices))
    new_indices = np.array(remaining_indices)[new_indices]  # Convert to original index space

    pseudo_config['sampled_indices'] += list(new_indices)
    #pseudo_config['sampled_indices'] = list(set(pseudo_config['sampled_indices']))

    final_indices = list(pseudo_config['sampled_indices'])[:sample_size]
    print(df.iloc[final_indices].head(10))

6
          0         1         2
6  0.431945  0.291229  0.611853
7  0.139494  0.292145  0.366362
8  0.456070  0.785176  0.199674
9  0.514234  0.592415  0.046450
3  0.708073  0.020584  0.969910
4  0.832443  0.212339  0.181825


In [157]:


def perform_cumulative_sampling(config, df):
    """
    """
    target_sample_size = config["data"]['n_training_patients']
    print(" ALREADY SAMPLED: ", config["data"]['sampled_indices'])
    remaining_indices = list(set(range(len(df))) - set(config["data"]['sampled_indices']))
    n_required_samples = target_sample_size - len(config["data"]['sampled_indices'])
    print("remaining_indices", remaining_indices)
    print(n_required_samples,)
    #remaining_indices = list(set(range(len(df))))

    if n_required_samples == len(remaining_indices):
        new_indices = remaining_indices
    elif n_required_samples < 0:
        raise ValueError(f"Number of required samples is less than 0. There is not enough training data to sample {target_sample_size} patients.")
    else:
        shuffle_split = ShuffleSplit(n_splits=1, train_size=n_required_samples) # , random_state=config['general']['seed'])
        new_indices, _ = next(shuffle_split.split(remaining_indices))
        new_indices = np.array(remaining_indices)[new_indices]  # Convert to original index space

    print(config["data"]['sampled_indices'], new_indices)
    config["data"]['sampled_indices'] += list(new_indices)
    config["data"]['sampled_indices'] = list(set(config["data"]['sampled_indices']))

    final_indices = list(config["data"]['sampled_indices'])[:target_sample_size]

    config["data"]['sampled_indices'] = final_indices
    
    return df.iloc[final_indices]


np.random.seed(42)
X = np.random.rand(4, 3)  # 10 samples, 3 features
df = pd.DataFrame(X)

pseudo_config = {
    'general' : 
     {
        "experiment_name" : "TEST_experiment",
        "trialNumber" : "?",
        "seed" : 42,
    },
    "data" : {
        "sampled_indices" : [],
        #"n_training_patients" : 3
      },
    "paths" : {
        "results" : "directory"
        }
    }


data_amounts = [2, 3, 4]



seeds = [42, 101]

for seed in seeds:
    #seed = i
    pseudo_config['general']['seed'] = seed
    pseudo_config["data"]['sampled_indices'] = []

    for data_amount in data_amounts:
        print(seed, data_amount)
        pseudo_config["data"]['n_training_patients'] = data_amount
        #pseudo_config["data"]['sampled_indices'] = []
        #print("----")
        
        sample = perform_cumulative_sampling(pseudo_config, df)

        experiment_dir = os.path.join(pseudo_config["paths"]["results"], pseudo_config["general"]["experiment_name"])
        folder_dir = os.path.join(experiment_dir, f"n_{pseudo_config["data"]['n_training_patients']}", f"{pseudo_config["general"]["seed"]}")
        print(folder_dir)

        #print(sample.head(10))
        print(pseudo_config["data"]['sampled_indices'])
        print("----\n")
    print("XXXXXXXXXXXXXXXX\n")


42 2
 ALREADY SAMPLED:  []
remaining_indices [0, 1, 2, 3]
2
[] [1 3]
directory\TEST_experiment\n_2\42
[1, 3]
----

42 3
 ALREADY SAMPLED:  [1, 3]
remaining_indices [0, 2]
1
[1, 3] [2]
directory\TEST_experiment\n_3\42
[1, 2, 3]
----

42 4
 ALREADY SAMPLED:  [1, 2, 3]
remaining_indices [0]
1
[1, 2, 3] [0]
directory\TEST_experiment\n_4\42
[0, 1, 2, 3]
----

XXXXXXXXXXXXXXXX

101 2
 ALREADY SAMPLED:  []
remaining_indices [0, 1, 2, 3]
2
[] [0 3]
directory\TEST_experiment\n_2\101
[0, 3]
----

101 3
 ALREADY SAMPLED:  [0, 3]
remaining_indices [1, 2]
1
[0, 3] [2]
directory\TEST_experiment\n_3\101
[0, 2, 3]
----

101 4
 ALREADY SAMPLED:  [0, 2, 3]
remaining_indices [1]
1
[0, 2, 3] [1]
directory\TEST_experiment\n_4\101
[0, 1, 2, 3]
----

XXXXXXXXXXXXXXXX



In [180]:
def perform_cumulative_sampling2(config, df, sampled_indices, target_sample_size):
    """
    """
    
    remaining_indices = list(set(range(len(df))) - set(sampled_indices))  # determine which patients have not already been sampled
    n_required_samples = target_sample_size - len(sampled_indices)  # how many more patients  we need to sample
    

    if n_required_samples == len(remaining_indices):
        new_indices = remaining_indices
    elif n_required_samples < 0:
        # if the number of required samples is less than 0, raise an error
        # i.e. there is not enough training data to sample the target number of patients
        raise ValueError(f"Number of required samples is less than 0. There is not enough training data to sample {target_sample_size} patients.")
    else:
        # shuffle the indicies of the remaining patients and select the required number of samples
        shuffle_split = ShuffleSplit(n_splits=1, train_size=n_required_samples) # , random_state=config['general']['seed'])
        new_indices, _ = next(shuffle_split.split(remaining_indices))
        new_indices = np.array(remaining_indices)[new_indices]  # Convert back to the original index space

    # update the list of sampled indices with the new_indices
    sampled_indices += list(new_indices)

    # check that the number of unique indices is equal to the target sample size
    assert len(sampled_indices) == len(set(sampled_indices)) == target_sample_size
    
    return df.iloc[sampled_indices], sampled_indices

np.random.seed(42)
X = np.random.rand(4, 3)  # 10 samples, 3 features
df = pd.DataFrame(X)

pseudo_config = {
    'general' : 
     {
        "experiment_name" : "TEST_experiment",
        "trialNumber" : "?",
        "seed" : 42,
    },
    "data" : {
        "sampled_indices" : [],
        #"n_training_patients" : 3
      },
    "paths" : {
        "results" : "directory"
        }
    }


data_amounts = [2, 3, 4]

pseudo_config["data"]['n_training_patients_sets'] = data_amounts

seeds = [42, 101]

datasets_list = []

for seed in seeds:
    #seed = i
    pseudo_config['general']['seed'] = seed
    pseudo_config["data"]['sampled_indices'] = []

    sampled_indices = []

    for data_amount in pseudo_config["data"]['n_training_patients_sets']:
        print(seed, data_amount)
        pseudo_config["data"]['n_training_patients'] = data_amount
        #pseudo_config["data"]['sampled_indices'] = []
        #print("----")
        
        sample, sampled_indices = perform_cumulative_sampling2(pseudo_config, df, sampled_indices, data_amount)
        print('main', sampled_indices)
        datasets_list.append(sample)

        

        #print(sample.head(10))
        
        print("----\n")
    print("XXXXXXXXXXXXXXXX\n")


    for fold_idx, D_set in enumerate(datasets_list):
        n_patients = pseudo_config["data"]['n_training_patients_sets'][fold_idx]
        pseudo_config["data"]['n_training_patients'] = n_patients

        experiment_dir = os.path.join(pseudo_config["paths"]["results"], pseudo_config["general"]["experiment_name"])
        folder_dir = os.path.join(experiment_dir, f"n_patients_{pseudo_config["data"]['n_training_patients_sets'][fold_idx]}", f"seed_{pseudo_config["general"]["seed"]}")
        print(folder_dir)
        print(len(D_set))

        #print(fold_idx, D_set)
        print("----\n")

42 2
main [1, 3]
----

42 3
main [1, 3, 2]
----

42 4
main [1, 3, 2, 0]
----

XXXXXXXXXXXXXXXX

directory\TEST_experiment\n_patients_2\seed_42
2
----

directory\TEST_experiment\n_patients_3\seed_42
3
----

directory\TEST_experiment\n_patients_4\seed_42
4
----

101 2
main [0, 3]
----

101 3
main [0, 3, 2]
----

101 4
main [0, 3, 2, 1]
----

XXXXXXXXXXXXXXXX

directory\TEST_experiment\n_patients_2\seed_101
2
----

directory\TEST_experiment\n_patients_3\seed_101
3
----

directory\TEST_experiment\n_patients_4\seed_101
4
----



IndexError: list index out of range

In [159]:
data_amounts = [2, 4]


for data_amount in data_amounts:
    print(data_amount)
    pseudo_config["data"]['n_training_patients'] = data_amount
    pseudo_config["data"]['sampled_indices'] = []

    for i in range(0, 2):
        print("----")
        pseudo_config['general']['seed'] = i
        pseudo_config["data"]['sampled_indices'] = []
        sample = perform_cumulative_sampling(pseudo_config, df)

        #print(sample.head(10))
        print(pseudo_config["data"]['sampled_indices'])
        print("----")

2
----


TypeError: perform_cumulative_sampling() missing 1 required positional argument: 'sampled_indices'

In [76]:
pseudo_config = {'general' : {
    "experiment_name" : "TEST_experiment",
    "trialNumber" : "?",
    "seed" : 42,
    },
    "data" : {"sampled_indices" : [],
      "n_training_patients" : 8}
    }


sample = perform_cumulative_sampling(pseudo_config, df)
print(sample.head(10))

8
           0         1         2
86  0.570061  0.097176  0.615007
82  0.428184  0.966655  0.963620
20  0.388677  0.271349  0.828738
60  0.341066  0.113474  0.924694
71  0.224269  0.712179  0.237249
14  0.034389  0.909320  0.258780
92  0.798295  0.649964  0.701967
51  0.489453  0.985650  0.242055
