In [ ]:
import torch
import numpy as np
import pandas as pd

In [22]:
train_labels = torch.as_tensor([0, 1, -1, 1, 0, 0, -1, np.nan])  # Note: `None` value is not valid
train_outputs = torch.as_tensor([[0.9, 0.1],
                          [0.7, 0.3],
                          [0.4, 0.6],  # -1
                          [0.8, 0.20],
                          [0.75, 0.25],
                          [1.0, 0.0],
                          [0.6, 0.4],  # -1
                          [0.99, 0.01]])  # -1


In [23]:
train_labels

tensor([ 0.,  1., -1.,  1.,  0.,  0., -1., nan])

In [24]:
train_outputs

tensor([[0.9000, 0.1000],
        [0.7000, 0.3000],
        [0.4000, 0.6000],
        [0.8000, 0.2000],
        [0.7500, 0.2500],
        [1.0000, 0.0000],
        [0.6000, 0.4000],
        [0.9900, 0.0100]])

In [25]:
train_outputs[torch.isin(train_labels, torch.as_tensor([0, 1]))]

tensor([[0.9000, 0.1000],
        [0.7000, 0.3000],
        [0.8000, 0.2000],
        [0.7500, 0.2500],
        [1.0000, 0.0000]])

In [15]:
torch.tensor([[0.3156, 0.3269],
        [0.1898, 0.3086],
        [0.2465, 0.2684],
        [0.2055, 0.2004]]).shape

torch.Size([4, 2])